version: "3.9"

services:
  postgres:
    container_name: nest-clean-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nestcleandb
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
